version: '3.9'

services:
  go-app:
    container_name: go-app
    image: gin-gorm/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@go_db:5432/postgres?sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go_db_test:
    container_name: go_db_test
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432" # Map testing DB to a different port
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
